import { useEffect, useState } from 'react';
import { useOrganizationPage, type OrganizationItem } from '../lib/organization';
import type { SearchMode } from '../lib/resourceSearch';
/** Shared search options; scope is controlled by the visible destination. */
export default function ResourceSearchOptions({mode,onMode,collection,onCollection}:{mode:SearchMode;onMode:(mode:SearchMode)=>void;collection:OrganizationItem|null;onCollection:(item:OrganizationItem|null)=>void}) {
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(query.trim());setPage(0);},150);return()=>clearTimeout(timer);},[query]);
 const result=useOrganizationPage('collection',search,page);
 return <><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={mode==='content'} onChange={e=>onMode(e.target.checked?'content':'title')}/>Include saved note text</label><div className="border-t border-border pt-3 space-y-2"><p className="text-sm font-medium">Search in</p><button className="library-button w-full" aria-pressed={!collection} onClick={()=>onCollection(null)}>Entire workspace</button>{collection&&<p className="text-xs text-[var(--text-secondary)]">Selected: {collection.name}</p>}<input className="organization-input w-full" aria-label="Find collection scope" placeholder="Find a collection…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="max-h-40 overflow-auto space-y-1">{query.trim()===search&&result.data?.items.map(item=><button key={item.id} className="library-button w-full" aria-pressed={collection?.id===item.id} onClick={()=>onCollection(item)}>{item.name}</button>)}</div>{result.loading&&<p className="text-xs">Loading collections…</p>}{result.error&&<p role="alert" className="text-sm">{result.error}<button className="library-button" onClick={result.retry}>Retry scopes</button></p>}{!result.loading&&!result.error&&result.data?.items.length===0&&<p className="text-xs">No collections match.</p>}{(result.data?.totalPages??0)>1&&<div className="flex gap-2"><button className="library-button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous collections</button><button className="library-button" disabled={page+1>=(result.data?.totalPages??0)} onClick={()=>setPage(p=>p+1)}>Next collections</button></div>}</div></>;
}
