// Focused native performance session against marked Atlas only, never personal data.
import {spawn,execFileSync} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {createServer} from 'node:net';import {performance} from 'node:perf_hooks';import {fileURLToPath} from 'node:url';
import {rootGuard,defaultRoot,atomic,prepareProfile} from './atlas.mjs';
const root=await rootGuard(defaultRoot),manifest=JSON.parse(await readFile(join(root,'manifest.json'),'utf8'));
await prepareProfile(root);
const socket=createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
const app=fileURLToPath(new URL('../releases/win-unpacked/Vaultor.exe',import.meta.url));const env={...process.env,VAULTOR_DESKTOP_TEST_DIRECTORY:join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;delete env.VAULTOR_UPDATE_RELAUNCH_CHECK;
const appVersion=JSON.parse(await readFile(fileURLToPath(new URL('../releases/win-unpacked/resources/app/package.json',import.meta.url)),'utf8')).version;
const began=performance.now(),child=spawn(app,[`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1'],{env,windowsHide:true,stdio:'ignore'});
let ws,seq=0;const pending=new Map(),report={seed:manifest.seed,started:new Date().toISOString(),app:appVersion,samples:{},limitations:['New process with retained Atlas session; OS/disk caches are not flushed.','Native main-process IPC requests are not visible in renderer CDP; API benchmark records explicit request counts.','412px desktop viewport is not Android verification; slow-network scenarios are documented but not measured.','Memory is sampled process-tree working set/private bytes, not a continuous peak or verified cache-release bound.','Image opening measures editor and image DOM readiness, not complete decoding of every image.']};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function command(method,params={}){const n=++seq;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(n);reject(new Error('CDP timed out: '+method));},60000);pending.set(n,{resolve:value=>{clearTimeout(timeout);resolve(value);},reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function evaluate(expression){const value=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw new Error(value.exceptionDetails.text+' '+value.exceptionDetails.exception?.description);return value.result?.value;}
async function wait(expression){for(let n=0;n<600;n++){if(await evaluate(expression).catch(()=>false))return;
 if(n%20===0&&await evaluate("document.body.innerText.includes('Server check failed (409)')").catch(()=>false)){report.startupBusyRetries=(report.startupBusyRetries??0)+1;await evaluate("document.querySelector('.desktop-profile-open:not(:disabled)')?.click()");}
 await sleep(100);}throw new Error('Atlas native condition timed out: '+expression);}
async function measure(name,work){const at=performance.now();await work();report.samples[name]=performance.now()-at;console.log('Atlas native '+name+': '+Math.round(report.samples[name])+'ms');}
async function screenshot(name){await sleep(250);const result=await command('Page.captureScreenshot',{format:'png'});await writeFile(join(root,name+'.png'),Buffer.from(result.data,'base64'));}
async function memory(){if(process.platform!=='win32')return {unavailable:'Windows memory collector only'};const code=`$taskPid=${child.pid}; $items=Get-CimInstance Win32_Process; $ids=@($taskPid); do {$next=@($items|Where-Object {$_.ParentProcessId -in $ids -and $_.ProcessId -notin $ids}|Select-Object -ExpandProperty ProcessId);$ids+=$next} while($next.Count); @(Get-Process -Id $ids -ErrorAction SilentlyContinue|Select-Object ProcessName,WorkingSet64,PrivateMemorySize64)|ConvertTo-Json -Compress`;return JSON.parse(execFileSync('powershell',['-NoProfile','-Command',code],{encoding:'utf8',windowsHide:true}));}
try{
 let target;for(let n=0;n<600;n++){try{const list=await(await fetch(`http://127.0.0.1:${port}/json`)).json();target=list.find(t=>t.type==='page'&&t.url.startsWith('vaultor:'));if(target)break;}catch{}await sleep(100);}if(!target)throw new Error('Atlas CDP target missing');
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true});});ws.addEventListener('message',event=>{const value=JSON.parse(event.data);const item=pending.get(value.id);if(item){pending.delete(value.id);value.error?item.reject(new Error(value.error.message)):item.resolve(value.result);}});
 await wait("Boolean(document.querySelector('.sidebar-nav'))");
 await evaluate("[...document.querySelectorAll('.sidebar-nav')].find(b=>b.textContent.trim()==='Library')?.click()");
 await wait("document.querySelectorAll('.library-resource').length===100");report.samples.startupUsableMs=performance.now()-began;report.memoryBefore=await memory();await screenshot('atlas-library');
 await measure('recentDestinationMs',async()=>{await evaluate("[...document.querySelectorAll('.sidebar-nav')].find(b=>b.textContent.trim()==='Recent').click()");await wait("document.querySelector('.library-heading h1')?.textContent==='Recently opened'&&document.querySelectorAll('.library-resource').length===100");});
 await measure('pinnedDestinationMs',async()=>{await evaluate("[...document.querySelectorAll('.sidebar-nav')].find(b=>b.textContent.trim()==='Pinned').click()");await wait("['Pinned','Pinned shortcuts'].includes(document.querySelector('.library-heading h1')?.textContent)&&document.querySelectorAll('.library-resource').length>0");});
 const openStart="[...document.querySelectorAll('.sidebar-item,.sidebar-resource,.library-resource')].find(b=>b.textContent.includes('Atlas — Start here'))";
 // Use title-only Library search through its React input rather than private app state.
 await evaluate("[...document.querySelectorAll('.sidebar-nav')].find(b=>b.textContent.trim()==='Library').click()");await wait("document.querySelector('.library-heading h1')?.textContent==='Library'");
 await evaluate("(()=>{const input=document.querySelector('input[placeholder=\"Search resource titles…\"],input[placeholder=\"Search resource titles...\"]');if(!input)throw new Error('Missing title search');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Atlas — Start here');input.dispatchEvent(new Event('input',{bubbles:true}));})()");
 await wait("[...document.querySelectorAll('.library-resource')].some(b=>b.textContent.includes('Atlas — Start here'))");
 await measure('imageHeavyOpenMs',async()=>{await evaluate(openStart+'.click()');await wait("document.querySelector('.tiptap')?.editor?.getJSON().content[0].content[0].text==='Atlas — Start here'");await wait("document.querySelectorAll('.tiptap img').length>=3");});
 await screenshot('atlas-images');report.memoryImages=await memory();
 await measure('journey200VisitsMs',async()=>{for(let n=0;n<199;n++){const before=await evaluate("document.querySelector('.journey-current button').textContent");await evaluate("document.querySelector('.tiptap .resource-link-chip').click()");await wait(`document.querySelector('.journey-current button')?.textContent!==${JSON.stringify(before)}`);}});
 const steps=await evaluate("document.querySelector('[aria-label=\"Show full journey\"]').title");if(steps!=='200 of 200 steps')throw new Error('Journey bound differs: '+steps);report.journey=steps;await screenshot('atlas-journey');
 await measure('sharedNoteViewsMs',async()=>{
  await evaluate("document.querySelector('.tiptap .resource-link-chip').dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}))");await wait("document.querySelectorAll('.tiptap').length===2");
  // Navigate the new pane twice around the 3-cycle to show the same original in both panes.
  for(let n=0;n<2;n++){const before=await evaluate("document.querySelector('.journey-current button').textContent");await evaluate("document.querySelectorAll('.tiptap')[1].querySelector('.resource-link-chip').click()");await wait(`document.querySelector('.journey-current button')?.textContent!==${JSON.stringify(before)}`);}
  await wait("JSON.stringify(document.querySelectorAll('.tiptap')[0].editor.getJSON())===JSON.stringify(document.querySelectorAll('.tiptap')[1].editor.getJSON())");
 });
 await evaluate("document.querySelectorAll('.tiptap')[0].editor.commands.insertContent('Atlas temporary shared benchmark edit')");await wait("document.querySelectorAll('.tiptap')[1].innerText.includes('Atlas temporary shared benchmark edit')");await evaluate("document.querySelectorAll('.tiptap')[1].editor.commands.undo()");await wait("![...document.querySelectorAll('.tiptap')].some(e=>e.innerText.includes('Atlas temporary shared benchmark edit'))");report.sharedUndo=true;report.memoryShared=await memory();await screenshot('atlas-shared');
 await command('Emulation.setDeviceMetricsOverride',{width:412,height:915,deviceScaleFactor:1,mobile:false});await screenshot('atlas-narrow');report.narrowViewport={width:412,height:915};
 await sleep(1000);await evaluate("window.vaultorDesktop.hostAction('stop')");await wait("(async()=>((await window.vaultorDesktop.localStatus()).value.status==='stopped'))()");report.hostStoppedSafely=true;
 await atomic(join(root,'native-report.json'),report);console.log('Atlas native baseline passed.');
}catch(e){report.failure=e.message;report.visibleFailure=await evaluate("document.body.innerText.slice(0,1500)").catch(()=>null);await screenshot('atlas-native-failure').catch(()=>{});await atomic(join(root,'native-report.json'),report);throw e;}
finally{if(ws?.readyState===1){await evaluate("window.vaultorDesktop.hostAction('stop')").catch(()=>{});ws.close();}child.kill();}
