// Same verified synthetic corpus, fresh owned storage. Never opens the user's Atlas or personal database.
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,cp,mkdir,realpath} from 'node:fs/promises';
import {join,resolve} from 'node:path';import {tmpdir,cpus,totalmem,release} from 'node:os';
import {fileURLToPath} from 'node:url';import {createHash,randomUUID} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {OwnedServer} from '../src/owned-server.mjs';import {defaultRoot,rootGuard,prepareProfile,id} from './atlas.mjs';
const seed='atlas-2026-10-v1',manifest=JSON.parse(await readFile(join(defaultRoot,'manifest.json'))),zip=await readFile(join(defaultRoot,'baseline.zip'));
assert.equal(manifest.seed,seed);assert.equal(createHash('sha256').update(zip).digest('hex'),manifest.archive.sha256);
const resume=process.argv.includes('--resume')?process.argv[process.argv.indexOf('--resume')+1]:null;
const root=resume?resolve(resume):await mkdtemp(join(tmpdir(),'vaultor-sprint5-scale-')),bundle=process.env.VAULTOR_BUILD_BUNDLE??fileURLToPath(new URL('../bundle/',import.meta.url));
let prior;if(resume){prior=JSON.parse(await readFile(join(root,'report.json')));assert.ok(root.startsWith(join(tmpdir(),'vaultor-sprint5-scale-')));assert.equal(await realpath(root),root);assert.equal(prior.root,root);assert.equal(prior.seed,seed);assert.equal(prior.archiveHash,manifest.archive.sha256);}
const owned=new OwnedServer({bundle,data:join(root,'data')}),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const report={seed,version:'0.7.1',root,archiveHash:manifest.archive.sha256,hardware:{cpu:cpus()[0].model,ram:totalmem(),os:release()},requests:0,busyRetries:0,statusSamples:[],coverageSamples:[],memorySamples:[],queries:{},limitations:'New processes; disk/OS cache not flushed. Six warm samples are median/max, not p95. Memory samples are parent JVM working set only, not peak/child/RSS totals. No real Mac/LAN/Android verification.'};
async function request(path,method='GET',body){for(let n=0;n<600;n++){const form=body instanceof FormData;report.requests++;const r=await fetch(owned.address+'/api'+path,{method,headers:{'X-Vaultor-Owner':owned.accessKey,'X-Vaultor-Protocol':'3','X-Request-ID':randomUUID(),...(!form&&body?{'Content-Type':'application/json'}:{})},body:body?(form?body:JSON.stringify(body)):undefined,signal:AbortSignal.timeout(15000)});if(r.status===409||r.status===503){report.busyRetries++;await sleep(100);continue;}const value=await r.json();assert.ok(r.ok,path+' '+r.status);return value;}throw new Error('Maintenance retry exhausted: '+path);}
function memory(){return Number(execFileSync('powershell.exe',['-NoProfile','-Command',`(Get-Process -Id ${owned.child.pid}).WorkingSet64`],{encoding:'utf8',windowsHide:true}).trim());}
try{
 const start=performance.now();await owned.start();report.serverStartMs=performance.now()-start;
 if(!resume){
 const form=new FormData();form.set('file',new Blob([zip],{type:'application/zip'}),'atlas.zip');const review=await request('/imports/preview','POST',form);const began=performance.now();await request('/imports/'+review.operation.id+'/commit','POST',{mode:'replace',confirmation:'replace'});
 let finished=false;for(let n=0;n<1200;n++){const at=performance.now(),op=await request('/operations/'+review.operation.id);report.statusSamples.push({ms:performance.now()-at,status:op.status,phase:op.phase});if(op.status==='SUCCEEDED'){finished=true;break;}assert.notEqual(op.status,'FAILED',op.detail);await sleep(100);}assert.ok(finished,'Import did not settle');report.importMs=performance.now()-began;
 }else{report.priorObservation=prior;report.resumed=true;}
 assert.equal((await request('/resources?size=1')).totalItems,5000);
 const indexStart=performance.now();for(let n=0;n<120;n++){const coverage=(await request('/diagnostics/search')).files;report.coverageSamples.push({ms:performance.now()-indexStart,...coverage});if(n%6===0)report.memorySamples.push({ms:performance.now()-indexStart,workingSet:memory()});if(coverage.queued+coverage.indexing===0){report.indexSettled=true;break;}await sleep(5000);}report.indexObservationMs=performance.now()-indexStart;
 const cases={library:'/resources?size=100',recent:'/resources?sort=recent&size=100',pins:'/organization/pins?size=100',notes:'/resources?type=note&size=100',collection:'/resources?collection='+id('collection',0)+'&size=100',title:'/resources?q=field&size=100',content:'/resources/query?q=observations&size=100',fileContent:'/resources/query?q=habitat&size=100',tags:'/tags/browse?size=100',allTags:'/tags',references:'/resources/'+id('image',0)+'/references?direction=incoming&size=100'};
 for(const [name,path]of Object.entries(cases)){const samples=[];for(let n=0;n<7;n++){const at=performance.now(),page=await request(path);samples.push(performance.now()-at);if(name==='references')report.referencesTotal=page.totalItems;}const warm=samples.slice(1).sort((a,b)=>a-b);report.queries[name]={samples,firstMs:samples[0],warmMedianMs:(warm[2]+warm[3])/2,warmMaxMs:warm.at(-1),requests:7};}
 if(process.argv.includes('--tail')){report.tail={};for(const name of ['content','references']){const samples=[];for(let i=0;i<100;i++){const at=performance.now();await request(cases[name]);samples.push(performance.now()-at);}const sorted=[...samples].sort((a,b)=>a-b);report.tail[name]={samples,median:(sorted[49]+sorted[50])/2,p95:sorted[94],max:sorted[99],requests:100};}report.tailLimit='100 sequential warmed HTTP samples; empirical p95 only, not production percentile or cold/cache/concurrency certification.';}
 report.success=true;await owned.stop();
 // Native follow-up receives a new marked copy, not either original fixture.
 const nativeRoot=join(defaultRoot,'sprint5-'+randomUUID());await mkdir(nativeRoot);await writeFile(join(nativeRoot,'atlas-owner.json'),JSON.stringify({seed,root:nativeRoot,small:false}));await rootGuard(nativeRoot);await writeFile(join(nativeRoot,'manifest.json'),JSON.stringify(manifest));await cp(join(root,'data'),join(nativeRoot,'profile','local-workspace'),{recursive:true});await prepareProfile(nativeRoot);report.nativeRoot=nativeRoot;
 console.log(JSON.stringify({report:root,nativeRoot,importMs:report.importMs,indexSettled:report.indexSettled,coverage:report.coverageSamples.at(-1),requests:report.requests}));
}catch(error){report.failure=error.message;throw error;}finally{await owned.stop();await writeFile(join(root,'report.json'),JSON.stringify(report,null,2));}
