const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('vaultorDesktop', Object.freeze({
  bootstrap: () => ipcRenderer.invoke('desktop:bootstrap'),
  localStatus: () => ipcRenderer.invoke('desktop:local-status'),
  hosting: () => ipcRenderer.invoke('desktop:hosting'),
  login: enabled => ipcRenderer.invoke('desktop:login', enabled),
  hostAction: action => ipcRenderer.invoke('desktop:host-action', action),
  pickFiles: value => ipcRenderer.invoke('desktop:pick-files', value),
  readFile: value => ipcRenderer.invoke('desktop:read-file', value),
  beginSave: value => ipcRenderer.invoke('desktop:begin-save', value),
  saveChunk: value => ipcRenderer.invoke('desktop:save-chunk', value),
  finishSave: value => ipcRenderer.invoke('desktop:finish-save', value),
  cancelSave: value => ipcRenderer.invoke('desktop:cancel-save', value),
  fileAction: value => ipcRenderer.invoke('desktop:file-action', value),
  cancelFile: value => ipcRenderer.invoke('desktop:cancel-file',value),
  releaseFile: value => ipcRenderer.invoke('desktop:release-file', value),
  onQuitRequest: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('desktop:quit-request',listener);return()=>ipcRenderer.removeListener('desktop:quit-request',listener); },
  quitReply: value => ipcRenderer.invoke('desktop:quit-reply',value),
  onResume: callback => { const listener=()=>callback();ipcRenderer.on('desktop:resume',listener);return()=>ipcRenderer.removeListener('desktop:resume',listener); },
  addProfile: profile => ipcRenderer.invoke('desktop:add-profile', profile),
  probe: id => ipcRenderer.invoke('desktop:probe', id),
  activate: ticket => ipcRenderer.invoke('desktop:activate', ticket),
  request: value => ipcRenderer.invoke('desktop:request', value),
  cancel: id => ipcRenderer.invoke('desktop:cancel', id),
  writeClipboard: text => ipcRenderer.invoke('desktop:clipboard', text),
}));
