const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('vaultorDesktop', Object.freeze({
  bootstrap: () => ipcRenderer.invoke('desktop:bootstrap'),
  updatesStatus:()=>ipcRenderer.invoke('desktop:updates-status'),
  updatesConfigure:feed=>ipcRenderer.invoke('desktop:updates-configure',feed),
  updatesCheck:()=>ipcRenderer.invoke('desktop:updates-check'),
  updatesDownload:()=>ipcRenderer.invoke('desktop:updates-download'),
  updatesCancel:()=>ipcRenderer.invoke('desktop:updates-cancel'),
  updatesImport:()=>ipcRenderer.invoke('desktop:updates-import'),
  updatesInstall:()=>ipcRenderer.invoke('desktop:updates-install'),
  updatesRestore:()=>ipcRenderer.invoke('desktop:updates-restore'),
  onUpdates:callback=>{const listener=(_event,value)=>callback(value);ipcRenderer.on('desktop:updates-state',listener);return()=>ipcRenderer.removeListener('desktop:updates-state',listener);},
  onUpdatesOpen:callback=>{const listener=()=>callback();ipcRenderer.on('desktop:updates-open',listener);return()=>ipcRenderer.removeListener('desktop:updates-open',listener);},
  localStatus: () => ipcRenderer.invoke('desktop:local-status'),
  onLocalStatus: callback => { const listener=(_event,value)=>callback(value);ipcRenderer.on('desktop:local-status',listener);return()=>ipcRenderer.removeListener('desktop:local-status',listener); },
  hosting: () => ipcRenderer.invoke('desktop:hosting'),
  login: enabled => ipcRenderer.invoke('desktop:login', enabled),
  hostAction: action => ipcRenderer.invoke('desktop:host-action', action),
  nearby: enabled => ipcRenderer.invoke('desktop:nearby', enabled),
  pairInspect: value => ipcRenderer.invoke('desktop:pair-inspect', value),
  pairEnroll: id => ipcRenderer.invoke('desktop:pair-enroll', id),
  pairStatus: id => ipcRenderer.invoke('desktop:pair-status', id),
  pairCancel: () => ipcRenderer.invoke('desktop:pair-cancel'),
  forget: id => ipcRenderer.invoke('desktop:forget', id),
  sharing: enabled => ipcRenderer.invoke('desktop:sharing', enabled),
  devices: () => ipcRenderer.invoke('desktop:devices'),
  decision: value => ipcRenderer.invoke('desktop:decision', value),
  revoke: id => ipcRenderer.invoke('desktop:revoke', id),
  certificate: () => ipcRenderer.invoke('desktop:certificate'),
  renewTrust: () => ipcRenderer.invoke('desktop:renew-trust'),
  openSharedBrowser: address => ipcRenderer.invoke('desktop:open-shared-browser', address),
  windowStatus: () => ipcRenderer.invoke('desktop:window-status'),
  windowAction: action => ipcRenderer.invoke('desktop:window-action', action),
  onWindowStatus: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('desktop:window-status',listener);return()=>ipcRenderer.removeListener('desktop:window-status',listener); },
  onConnections: callback => { const listener=()=>callback();ipcRenderer.on('desktop:connections',listener);return()=>ipcRenderer.removeListener('desktop:connections',listener); },
  pickFiles: value => ipcRenderer.invoke('desktop:pick-files', value),
  readFile: value => ipcRenderer.invoke('desktop:read-file', value),
  beginSave: value => ipcRenderer.invoke('desktop:begin-save', value),
  saveChunk: value => ipcRenderer.invoke('desktop:save-chunk', value),
  finishSave: value => ipcRenderer.invoke('desktop:finish-save', value),
  cancelSave: value => ipcRenderer.invoke('desktop:cancel-save', value),
  fileAction: value => ipcRenderer.invoke('desktop:file-action', value),
  cancelFile: value => ipcRenderer.invoke('desktop:cancel-file',value),
  releaseFile: value => ipcRenderer.invoke('desktop:release-file', value),
  onQuitRequest: callback => { const listener=(_event,value)=>callback(value); ipcRenderer.on('desktop:quit-request',listener);return()=>ipcRenderer.removeListener('desktop:quit-request',listener); },
  quitReply: value => ipcRenderer.invoke('desktop:quit-reply',value),
  onResume: callback => { const listener=()=>callback();ipcRenderer.on('desktop:resume',listener);return()=>ipcRenderer.removeListener('desktop:resume',listener); },
  addProfile: profile => ipcRenderer.invoke('desktop:add-profile', profile),
  authorizeLocal:id=>ipcRenderer.invoke('desktop:authorize-local',id),
  probe: id => ipcRenderer.invoke('desktop:probe', id),
  activate: ticket => ipcRenderer.invoke('desktop:activate', ticket),
  request: value => ipcRenderer.invoke('desktop:request', value),
  stream: value => ipcRenderer.invoke('desktop:stream', value),
  onStream: callback => {const listener=(_event,value)=>callback(value);ipcRenderer.on('desktop:stream-event',listener);return()=>ipcRenderer.removeListener('desktop:stream-event',listener);},
  cancel: id => ipcRenderer.invoke('desktop:cancel', id),
  writeClipboard: text => ipcRenderer.invoke('desktop:clipboard', text),
}));
